version: '3.8'
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080